<?php
/**
 * Copyright © 2019 CHK. All rights reserved.
 * See COPYING.txt for license details.
 *
 *
 * CHK_AmazonSNS extension
 * NOTICE OF LICENSE
 *
 * @category  CHK
 * @package   CHK_AmazonSNS
 * @author Koushik CH <info@chkoushik.com>
 */
?>
<div class="actions actions-get-auth-token sns">
    <div style="color: red" id="auth_token_result_sns" class="message-validation hide"></div>
    <button  class="action-validate-get-auth-token-sns" type="button"  id="<?php echo $block->getHtmlId() ?>">
        <span><?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script>
    require(['jquery'], function(jQuery){
        jQuery('.action-validate-get-auth-token-sns').click(function(){
            var sid = jQuery('#sendsms_integration_sns_sid').val();
            var token = jQuery('#sendsms_integration_sns_token').val();
            var number = jQuery('#sendsms_integration_sns_number').val();
            var data = {
                sid: sid,
                token : token,
                number : number,
                form_key: FORM_KEY
            };
            var url = '<?php echo $block->getUrl('sendsms/system_config/check'); ?>//';
            jQuery.ajax({
                type: "POST",
                url: url,
                data: data,
                showLoader: true,
                success: function(response){
                    var result_token = jQuery('#auth_token_result_sns');
                    var responseObj = JSON.parse(response);
                    console.log(responseObj);
                    if(responseObj.error == 1){
                        jQuery('#sendsms_sns_auth_token').val(responseObj.description);
                        result_token.removeClass('hide').addClass('error');
                        result_token.html(responseObj.description);
                    }else{
                        jQuery('#sendsms_sns_auth_token').val(responseObj.description);
                        jQuery('#<?php echo $block->getHtmlId() ?>').attr('disabled', 'disabled');
                        result_token.removeClass('hide').addClass('success');
                        result_token.html(responseObj.description);
                    }
                }
            });
        });
    });
</script>