<?php
/**
 * Copyright © 2019 CHK. All rights reserved.
 * See COPYING.txt for license details.
 *
 * CHK_AmazonSNS extension
 * NOTICE OF LICENSE
 *
 * @category SMS
 * @package  CHK_AmazonSNS
 * @author   Koushik CH <info@chkoushik.com>
 */
/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?php /* @escapoeNotVerified */ echo __('Account Information') ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?php echo $block->escapeHtml($block->getName()) ?><br>
                    <?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                    <?php $customer = $block->getCustomer();
                          $mobile = $customer->getCustomAttribute('mobile_numbers');
                          if (isset($mobile)) {
                              echo 'Mobile:' . $block->escapeHtml($mobile->getValue());
                    }?><br>
                </p>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/edit') ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Edit') ?></span>
                </a>
                <a href="<?php /* @escapeNotVerified */ echo $block->getChangePasswordUrl() ?>" class="action change-password">
                    <?php /* @escapeNotVerified */ echo __('Change Password') ?>
                </a>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Newsletters') ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?php /* @escapeNotVerified */ echo __('You subscribe to "General Subscription".') ?>
                        <?php else: ?>
                            <?php /* @escapeNotVerified */ echo __('You don\'t subscribe to our newsletter.') ?>
                        <?php endif; ?>
                    </p>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $block->getChildHtml('customer.account.dashboard.info.extra')?>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getUrl('newsletter/manage') ?>"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
